<a href="https://colab.research.google.com/github/jek5on/MH/blob/main/%D0%A1%D0%B2%D0%B0%D1%82%D0%B5%D0%BD%D0%BA%D0%BE_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лабораторна робота 1. Вступ до машинного навчання. Елементи лінійної алгебри.
#Варіант 26

#Завдання 1.
Створіть одновимірний масив (вектор) з оберненими значеннями факторіалів
натуральних чисел, починаючи з 1, та виведіть його значення

In [8]:
import numpy as np
from math import factorial

n = 10

inverse_factorials = np.array([1 / factorial(i) for i in range(1, n+1)])

print(inverse_factorials)

[1.00000000e+00 5.00000000e-01 1.66666667e-01 4.16666667e-02
 8.33333333e-03 1.38888889e-03 1.98412698e-04 2.48015873e-05
 2.75573192e-06 2.75573192e-07]


#Завдання 2.
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його квадратами
факторіалів кожного числа, починаючи з 1, та виведіть його значення.

In [6]:
import numpy as np
from math import factorial

matrix = np.array([[factorial(i)**2 for i in range(1, 10)]]).reshape(3, 3)

print(matrix)

[[           1            4           36]
 [         576        14400       518400]
 [    25401600   1625702400 131681894400]]


#Завдання 3.
Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 10 та знайдіть мін елемент.

In [13]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

min_element = np.min(matrix)

print("Масив:")
print(matrix)
print("Мінімальний елемент:", min_element)

Масив:
[[ 8  3  2]
 [ 5  5  7]
 [ 7  6 10]]
Мінімальний елемент: 2


#Завдання 4.
Створіть масив розміром 2x2, заповніть його випадковими дійсними числами від -1.2 до 1.2 та виведіть його значення.

In [16]:
import numpy as np

matrix = np.random.uniform(-1.2, 1.2, size=(2, 2))

print("Масив:")
print(matrix)


Масив:
[[ 0.79298527  1.11084426]
 [-0.61511661  0.89244131]]


#Завдання 5.
Створіть два однакових масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 10 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.

In [18]:
import numpy as np

array1 = np.random.randint(10, 16, size=5)
array2 = np.copy(array1)

sum_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("Результат додавання:", sum_result)
print("Результат віднімання:", subtraction_result)
print("Результат множення:", multiplication_result)


Масив 1: [13 14 11 10 10]
Масив 2: [13 14 11 10 10]
Результат додавання: [26 28 22 20 20]
Результат віднімання: [0 0 0 0 0]
Результат множення: [169 196 121 100 100]


#Завдання 6.
Створіть дві матриці 4х4, заповніть їх довільними цілими чслами від 10 до 100 та знайдіть їх добуток.

In [19]:
import numpy as np

matrix1 = np.random.randint(10, 101, size=(4, 4))
matrix2 = np.random.randint(10, 101, size=(4, 4))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)

Матриця 1:
[[55 26 14 99]
 [90 33 87 66]
 [18 52 76 76]
 [46 10 30 19]]
Матриця 2:
[[20 34 94 70]
 [96 14 81 25]
 [10 15 37 43]
 [68 63 39 57]]
Добуток матриць:
[[10468  8681 11655 10745]
 [10326  8985 16926 14628]
 [11280  7268 11680 10160]
 [ 3472  3351  6985  5843]]


#Завдання 7.
Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.


In [20]:
import numpy as np

matrix1 = np.random.randint(1, 6, size=(3, 2))

matrix2 = np.random.randint(1, 6, size=(2, 4))

product = np.dot(matrix1, matrix2)

print("Матриця 3x2:")
print(matrix1)
print("Матриця 2x4:")
print(matrix2)
print("Добуток матриць (3x4):")
print(product)

Матриця 3x2:
[[3 5]
 [5 1]
 [3 3]]
Матриця 2x4:
[[5 1 2 2]
 [3 2 5 4]]
Добуток матриць (3x4):
[[30 13 31 26]
 [28  7 15 14]
 [24  9 21 18]]


#Завдання 8.
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.


In [21]:
import numpy as np

matrix = np.random.randint(1, 13, size=(3, 3))

if np.linalg.det(matrix) == 0:
    print("Матриця є виродженою і не має оберненої матриці.")
else:
    inverse_matrix = np.linalg.inv(matrix)

    print("Матриця 3x3:")
    print(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)

Матриця 3x3:
[[ 9  3 12]
 [ 1  4  4]
 [ 4  1 10]]
Обернена матриця:
[[ 0.22222222 -0.11111111 -0.22222222]
 [ 0.03703704  0.25925926 -0.14814815]
 [-0.09259259  0.01851852  0.2037037 ]]


#Завдання 9.
Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

In [22]:
import numpy as np

matrix = np.random.randint(0, 2, size=(4, 4))

transposed_matrix = np.transpose(matrix)

print("Матриця 4x4:")
print(matrix)
print("Транспонована матриця:")
print(transposed_matrix)

Матриця 4x4:
[[0 1 0 0]
 [1 0 1 0]
 [1 1 0 0]
 [1 0 1 0]]
Транспонована матриця:
[[0 1 1 1]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 0 0]]


#Завдання 10.
Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, знайдіть добуток матриці на вектор.

In [23]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))

vector = np.random.uniform(0, 1, size=(4, 1))

product = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)
print("Вектор 4x1:")
print(vector)
print("Добуток матриці і вектора:")
print(product)

Матриця 3x4:
[[ 1  4  7  7]
 [ 8  9  7 10]
 [ 2 10  1  7]]
Вектор 4x1:
[[0.57005651]
 [0.95038356]
 [0.12557676]
 [0.98997594]]
Добуток матриці і вектора:
[[12.18045971]
 [23.89270092]
 [17.69935699]]


#Завдання 11.
Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, знайдіть добуток матриці на вектор.

In [24]:
import numpy as np

matrix = np.random.uniform(0, 1, size=(2, 3))

vector = np.random.randint(1, 11, size=(3, 1))

product = np.dot(matrix, vector)

print("Матриця 2x3:")
print(matrix)
print("Вектор 3x1:")
print(vector)
print("Добуток матриці і вектора:")
print(product)

Матриця 2x3:
[[0.79334109 0.54910722 0.31983122]
 [0.32420993 0.99255717 0.60066954]]
Вектор 3x1:
[[5]
 [3]
 [3]]
Добуток матриці і вектора:
[[6.57352075]
 [6.40072979]]


#Завдання 12.
Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 3та знайдіть добуток всіх елементів обох матриць.

In [25]:
import numpy as np

matrix1 = np.random.randint(1, 4, size=(3, 3))
matrix2 = np.random.randint(1, 4, size=(3, 3))

product_matrix1 = np.prod(matrix1)
product_matrix2 = np.prod(matrix2)

print("Матриця 1:")
print(matrix1)
print("Добуток всіх елементів Матриці 1:", product_matrix1)

print("Матриця 2:")
print(matrix2)
print("Добуток всіх елементів Матриці 2:", product_matrix2)

Матриця 1:
[[1 3 3]
 [2 3 2]
 [2 2 1]]
Добуток всіх елементів Матриці 1: 432
Матриця 2:
[[2 3 2]
 [2 3 2]
 [1 3 2]]
Добуток всіх елементів Матриці 2: 864


#Завдання 13.
Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від -5 до 5 та знайдіть добуток їх елементів.

In [26]:
import numpy as np

matrix1 = np.random.randint(-5, 6, size=(3, 3))
matrix2 = np.random.randint(-5, 6, size=(3, 3))

product_matrix1 = np.prod(matrix1)
product_matrix2 = np.prod(matrix2)

print("Матриця 1:")
print(matrix1)
print("Добуток всіх елементів Матриці 1:", product_matrix1)

print("Матриця 2:")
print(matrix2)
print("Добуток всіх елементів Матриці 2:", product_matrix2)

Матриця 1:
[[ 3 -1  5]
 [ 0 -4 -1]
 [ 0 -3  3]]
Добуток всіх елементів Матриці 1: 0
Матриця 2:
[[ 5  1  3]
 [ 5 -4 -1]
 [ 4  4 -1]]
Добуток всіх елементів Матриці 2: -4800


#Завдання 14.
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть середнє значення елементів на головній діагоналі.


In [27]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

diagonal_elements = np.diag(matrix)

mean_diagonal = np.mean(diagonal_elements)

print("Матриця 3x3:")
print(matrix)
print("Середнє значення елементів головної діагоналі:", mean_diagonal)

Матриця 3x3:
[[4 4 9]
 [7 3 3]
 [6 4 4]]
Середнє значення елементів головної діагоналі: 3.6666666666666665


#Завдання 15.
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить найменший елемент у кожному стовпці матриці.


In [28]:
import numpy as np

matrix = np.random.uniform(-1, 1, size=(3, 3))

min_elements = np.min(matrix, axis=0)

print("Матриця 3x3:")
print(matrix)
print("Вектор-стовпчик з найменшими елементами кожного стовпця:")
print(min_elements)

Матриця 3x3:
[[ 0.02904736  0.4330029  -0.09722506]
 [ 0.11255004 -0.55432771 -0.46473534]
 [ 0.31956393  0.23156733 -0.57549976]]
Вектор-стовпчик з найменшими елементами кожного стовпця:
[ 0.02904736 -0.55432771 -0.57549976]


#Висновок:
Під час виконання лабораторної роботи були вирішені кілька завдань, що допомогли краще зрозуміти основи роботи з масивами та матрицями за допомогою бібліотеки NumPy в Python:

1. **Одновимірний масив обернених факторіалів:** Ми створили масив, в якому зберігаються обернені значення факторіалів натуральних чисел, що показало, як працювати з факторіалами у Python.

2. **Матриця з квадратами факторіалів:** Було сформовано матрицю, де кожен елемент – це квадрат факторіала відповідного числа. Це допомогло закріпити навички роботи з двовимірними масивами.

3. **Масив з випадковими натуральними числа:** Ми заповнили масив випадковими натуральними числами і знайшли мінімальне значення серед них, що продемонструвало, як виконувати базові операції з масивами.

4. **Матриця з випадковими дійсними числами:** Створили матрицю з випадковими дійсними числами, що дозволило краще зрозуміти, як працювати з випадковими значеннями.

5. **Поелементні операції над масивами:** Провели операції додавання, віднімання та множення над двома однаковими масивами, що показало, як здійснювати арифметичні операції з масивами.

6. **Добуток матриць:** Знайшли добуток двох матриць розміром 4x4, що допомогло зрозуміти матричні обчислення.

7. **Множення матриць різних розмірів:** Виконали множення матриць розміром 3x2 і 2x4, що показало важливість відповідності розмірів при матричних операціях.

8. **Транспонування матриці:** Провели транспонування матриці розміром 4x4, що допомогло зрозуміти, як змінюється матриця при транспонуванні.

9. **Множення матриці на вектор:** Обчислили добуток матриці 3x4 на вектор 4x1, що продемонструвало, як матриці і вектори взаємодіють.

10. **Множення матриці на вектор з іншими розмірами:** Провели множення матриці 2x3 на вектор 3x1, що допомогло зрозуміти, як зміна розмірів впливає на результати.

11. **Добуток елементів матриць:** Знайшли добуток всіх елементів матриць з випадковими числами від -5 до 5, що дозволило дослідити, як негативні значення впливають на результати.

12. **Середнє значення головної діагоналі:** Обчислили середнє значення елементів головної діагоналі матриці 3x3, що показало, як працювати з діагональними елементами матриць.

13. **Найменші елементи в стовпцях матриці:** Знайшли найменші елементи в кожному стовпці матриці 3x3, що допомогло закріпити навички роботи з стовпцями матриць.

Ці завдання допомогли закріпити знання з роботи з матрицями та векторами, а також покращити навички в обчисленнях за допомогою NumPy.